Documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - CODE_OF_CONDUCT.md
          - CONTRIBUTING.md
          - CODE_REVIEW_CHECKLIST.md
          - RELEASE_PROCESS.md
          - docs-chef-io/**/*
