chef:
  endpoint: https://18.220.198.195
  superuser: pivotal
  ssl_verify_mode: verify_none
doorkeeper:
  administrators:
    - rainbowdash
email_from_address: 'Chef Notifications <notifications@chef.io>'
protocol: https
secret_key_base: CHANGE ME
zendesk:
  subdomain: getchef
